### ISSUE TITLE
Introducing submodules

### ISSUE THREAD

**Issue by Zsupi** [Nemeth-legtechnika/adminconsole#16]
## Todo:
- [ ] Create a new submodule for the main application
- [ ] Create a new dependencies.gradle file
- [ ] Move the common configurations to the root project
- [ ] Configure the docker files
- [ ] Test if the test controller is still working

## Source:
- [video](https://www.youtube.com/watch?v=pSKY3-K9_qc&ab_channel=NikolayPanyukov)
