### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by Zsupi** [Nemeth-legtechnika/adminconsole#22]
## Todo:
- [ ] Add the dependency
- [ ] Add google authorization [Java Master](https://www.youtube.com/watch?v=ouE3NuTzf20&ab_channel=JavaMaster) | [Kir-Dev](https://youtu.be/ojkaosU0Btw?si=59EOKlofZipK50-F&t=3480)
- [ ] Add email and password registration [baeldung](https://www.baeldung.com/spring-security-registration)
- [ ] Write tests
