### ISSUE TITLE
Configuration Service

### ISSUE THREAD

**Issue by Zsupi** [Nemeth-legtechnika/adminconsole#27]
## Todo:
- [ ]  Create a Configuration service for the application
- [ ] Change the Configuration object for the value, stored by the service
- [ ] Create Tests for Product using a mocked configuration service

## Resource:
- [ ] We can update the property values in runtime: https://www.codeproject.com/Questions/67995/can-we-update-properties-file-at-runtime
- [ ] We can refresh the properties with actuator

## Result:
- Created a new table in database
