### ISSUE TITLE
Database update

### ISSUE THREAD

**Issue by Zsupi** [Nemeth-legtechnika/adminconsole#34]
#### Todo:
- [x] Delete Attribute table
- [x] Introduce new Tag table for grouping products
- [x] Generate a new liquibase script
- [x] Resolve issue #30
