### ISSUE TITLE
Env file

### ISSUE THREAD

**Issue by Zsupi** [Nemeth-legtechnika/adminconsole#36]
## Todo:
- [ ] Create a new .env file
- [ ] Use it in docker
- [ ] Create new secret environment variables in github
- [ ] Use `me.paulschwarz:spring-dotenv` for intellij configuration
