### ISSUE TITLE
Database Migration

### ISSUE THREAD

**Issue by Zsupi** [Nemeth-legtechnika/adminconsole#4]
## Todo:
- [ ] Add liquibase to the project
- [ ] Create the Scheme of the database
- [ ] Create Entities
- [ ] Create a simple controller with repository to test it out
