### ISSUE TITLE
Default attributevalues

### ISSUE THREAD

**Issue by Zsupi** [Nemeth-legtechnika/adminconsole#40]
## Todo:
- [ ] Remove null default values
- [ ] Change nullable attributes to non-nullable ones
- [ ] Add default value to each
