### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by Zsupi** [Nemeth-legtechnika/adminconsole#5]
## Todo:
- [x] Create Docker-compose file to generate image from the project
- [x] Expand the Docker-compose file to generate a Postgres database
- [x] Try to add the database to IntelliJ
