### ISSUE TITLE
Valdation

### ISSUE THREAD

**Issue by Zsupi** [Nemeth-legtechnika/adminconsole#55]
#### Todo:

- [x] Check validity
- [x] Make sure that update fields can be null
- [x] But if it's not null, then it must be validated
- [x] The field's default value should be null
