### ISSUE TITLE
Repositories

### ISSUE THREAD

**Issue by Zsupi** [Nemeth-legtechnika/adminconsole#6]
## Todo:
- [ ] Introduce seeding into the project: #37 
- [ ] Create simple Crud repositories for all the Entities
- [ ] Create a simple Service and Controller layer to get access to the stored data
- [ ] Write tests for all the code
