### ISSUE TITLE
Change Tomcat to Jetty

### ISSUE THREAD

**Issue by Zsupi** [Nemeth-legtechnika/adminconsole#8]
## Todo:
- [x] Create a TestController to test out the working project
- [x] Change the Tomcat server to Jetty
- [x] Test if the created test controller is still working
